# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-24 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FantasyTeam",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(max_length=100)),
                ("owner", models.CharField(max_length=50)),
                ("draft_order", models.IntegerField(verbose_name="draft order")),
            ],
            options={
                "verbose_name": "Fantasy Team",
                "verbose_name_plural": "Fantasy Teams",
            },
        ),
        migrations.CreateModel(
            name="NFLTeam",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("abbrev", models.CharField(max_length=20, unique=True)),
                ("city", models.CharField(max_length=50)),
                ("byeweek", models.IntegerField(verbose_name="bye week")),
            ],
            options={
                "verbose_name": "NFL Team",
                "verbose_name_plural": "NFL Teams",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("firstname", models.CharField(max_length=50, null=True)),
                ("lastname", models.CharField(max_length=50, null=True)),
                ("pick", models.SmallIntegerField(null=True)),
                ("points", models.SmallIntegerField(null=True)),
                ("position", models.CharField(max_length=50)),
                ("rank", models.SmallIntegerField(null=True)),
                ("round", models.SmallIntegerField(null=True)),
                ("url", models.CharField(max_length=200, null=True)),
                ("picktime", models.DateTimeField(null=True)),
                ("yahooID", models.IntegerField(null=True)),
                ("avgPick", models.FloatField(null=True)),
                (
                    "fantasyteam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djleague.FantasyTeam",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_column="team",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djleague.NFLTeam",
                        to_field="abbrev",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
            },
        ),
    ]
