# Generated by Django 2.0.12 on 2020-08-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djleague", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="nfl_status",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
