name: Continuous Integration

on: [push]

jobs:
  run_tests:
    name: Run Django Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pipenv'
      - run: pipx install pipenv
      - run: pipenv install --ignore-pipfile

      - name: Run flake8
        run: pipenv run flake8

      - name: Run black
        run: pipenv run black --check --verbose .

      # The tests need some of the static files
      - name: Run manage.py collectstatic
        run: pipenv run ./manage.py collectstatic

      - name: Run tests
        run: pipenv run ./manage.py test --reverse --parallel
